services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontserverarroyoseco
    ports:
      - "4200:80"
    environment:
      API_BASE_URL: "http://34.58.123.99:8080"
    restart: unless-stopped
